<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace Kubnete\Content;

?>

<!-- Basic layout-->
<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">
            Form document creation
        </h5>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
                <li><a data-action="reload"></a></li>
                <li><a data-action="close"></a></li>
            </ul>
        </div>
    </div>

    <div class="panel-body">

        <p class="content-group-lg">Examples of standard form controls supported in an example form layout.
            Individual form controls automatically receive some global styling. All textual <code>&lt;input></code>,
            <code>&lt;textarea></code>, and <code>&lt;select></code> elements with <code>.form-control</code> are
            set to <code>width: 100%;</code> by default. Wrap labels and controls in <code>.form-group</code> for
            optimum spacing. Labels in horizontal form require <code>.control-label</code> class.</p>

        <?= $this->form()->openTag($this->form->setAttribute('class', 'form-horizontal')->prepare()); ?>

        <fieldset class="content-group">
            <legend class="text-bold hide">To create a new template</legend>

            <?php
            /** @var \Zend\Form\Element\Text $element */
            $element = $this->form->get('name')
                ->setAttribute('class', 'form-control')
                ->setLabelAttributes(['class' => 'control-label col-lg-2']);
            /** @var array $messages */
            $messages = $element->getMessages();
            /** @var array $hasError */
            $hasError = (bool)count($messages);
            ?>
            <div class="form-group <?php if ($hasError) :
                ?>has-warning has-feedback<?php
                                   endif; ?>">
                <?= $this->formLabel($element); ?>
                <div class="col-lg-10">
                    <?= $this->formElement($element); ?>
                    <?php if (count($messages)) : ?>
                        <div class="form-control-feedback">
                            <i class="icon-notification2"></i>
                        </div>
                        <span class="help-block">
                            <? foreach ($messages as $message): ?>
                                <?= $message; ?>
                            <? endforeach; ?>
                        </span>
                    <?php endif; ?>
                </div>
            </div>

            <?php
            /** @var \Zend\Form\Element\Text $element */
            $element = $this->form->get('uri')
                ->setAttribute('class', 'form-control')
                ->setLabelAttributes(['class' => 'control-label col-lg-2']);
            /** @var array $messages */
            $messages = $element->getMessages();
            /** @var array $hasError */
            $hasError = (bool)count($messages);
            ?>
            <div class="form-group <?php if ($hasError) :
                ?>has-warning has-feedback<?php
                                   endif; ?>">
                <?= $this->formLabel($element); ?>
                <div class="col-lg-10">
                    <?= $this->formElement($element); ?>
                    <?php if (count($messages)) : ?>
                        <div class="form-control-feedback">
                            <i class="icon-notification2"></i>
                        </div>
                        <span class="help-block">
                            <? foreach ($messages as $message): ?>
                                <?= $message; ?>
                            <? endforeach; ?>
                        </span>
                    <?php endif; ?>
                </div>
            </div>

            <?php
            /** @var \Zend\Form\Element\Text $element */
            $element = $this->form->get('document_type_id')
                ->setAttribute('class', 'form-control')
                ->setLabelAttributes(['class' => 'control-label col-lg-2']);
            /** @var array $messages */
            $messages = $element->getMessages();
            /** @var array $hasError */
            $hasError = (bool)count($messages);
            ?>
            <div class="form-group <?php if ($hasError) :
                ?>has-warning has-feedback<?php
                                   endif; ?>">
                <?= $this->formLabel($element); ?>
                <div class="col-lg-10">
                    <?= $this->formElement($element); ?>
                    <?php if (count($messages)) : ?>
                        <div class="form-control-feedback">
                            <i class="icon-notification2"></i>
                        </div>
                        <span class="help-block">
                            <? foreach ($messages as $message): ?>
                                <?= $message; ?>
                            <? endforeach; ?>
                        </span>
                    <?php endif; ?>
                </div>
            </div>

        </fieldset>

        <div class="text-right">
            <?= $this->formRow($this->form->get('id')); ?>
            <a href="<?= $this->url('backend/content/document'); ?>" class="btn btn-link">
                Return to the template list
            </a>
            <button type="submit" class="btn btn-primary">
                Submit form <i class="icon-arrow-right14 position-right"></i>
            </button>
        </div>

        <?= $this->form()->closeTag($this->form); ?>
    </div>
</div>
<!-- /basic layout -->

<?php
$this->headScript()
    ->appendFile($this->basePath('backend/assets/js/core/libraries/jquery_ui/interactions.min.js'))
    ->appendFile($this->basePath('backend/assets/js/plugins/forms/styling/uniform.min.js'))
    ->appendFile($this->basePath('backend/assets/js/plugins/forms/styling/switchery.min.js'))
    ->appendFile($this->basePath('backend/assets/js/plugins/forms/selects/select2.min.js'))
    ->appendFile($this->basePath('backend/assets/js/plugins/forms/selects/selectboxit.min.js'))
    ->appendFile($this->basePath('backend/assets/js/plugins/forms/selects/bootstrap_multiselect.js'))
    ->appendFile($this->basePath('backend/assets/js/plugins/forms/inputs/touchspin.min.js'))
    ->appendFile($this->basePath('backend/assets/js/plugins/uploaders/fileinput.min.js'))
    ->appendFile($this->basePath('backend/assets/js/plugins/forms/editable/editable.min.js'))
    ->appendFile($this->basePath('backend/assets/js/plugins/extensions/contextmenu.js'))
    ->appendFile($this->basePath('backend/assets/js/plugins/visualization/sparkline.min.js'))
    ->appendFile($this->basePath('backend/assets/js/pages/table_elements.js'))
?>
