<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

use MSBios\Document\Resource\Record\DataType;

$form = $this->form;
$form->prepare();

$this->headScript()
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switch.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switchery.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/uniform.min.js'));

?>

<div class="row">
    <div class="col-md-12">

        <?php if (! $this->paginator->count()) : ?>
            <div class="alert alert-info no-border" role="alert">
                <h4><?= $this->translate('Information message'); ?></h4>
                <p><?= $this->translate('The database is not created at the moment no datatypes, click "Create new datatype" to start working with the datatype.'); ?></p>
                <p>
                    <?php if ($this->isAllowed($this->config->get('resource'), 'add')) : ?>
                        <a href="<?= $this->url($this->config->get('route_name'), ['action' => 'add']); ?>"
                           class="btn btn-info"><?= $this->translate('Create new theme'); ?></a>
                    <?php endif; ?>
                </p>
            </div>

        <?php else : ?>
            <div class="panel panel-flat">

                <div class="panel-heading">
                    <h6 class="panel-title">
                        &nbsp<a class="heading-elements-toggle"><i class="icon-more"></i></a>
                    </h6>
                    <div class="heading-elements">
                        <div class="heading-btn">

                            <?= $this->form()->openTag((new \Zend\Form\Form)->prepare()->setAttributes([
                                'class' => 'heading-form',
                                'method' => 'GET'
                            ]));
                            ?>

                            <div class="form-group has-feedback">
                                <?= $this->formSearch(
                                    (new \Zend\Form\Element\Search('q'))->setAttributes([
                                        'class' => 'form-control',
                                        'placeholder' => $this->translate('Search...')
                                    ])
                                ); ?>

                                <div class="form-control-feedback">
                                    <i class="icon-search4 text-size-base text-muted"></i>
                                </div>
                            </div>

                            <?= $this->form()->closeTag(); ?>

                            &nbsp;

                            <button data-toggle="modal"
                                    data-target="#modal-item-add"
                                    class="btn btn-success">
                                <?= $this->translate('Create data type'); ?>
                            </button>

                            <div id="modal-item-add" class="modal fade">
                                <div class="modal-dialog modal-md">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">×</button>
                                            <h5 class="modal-title">Create new data type record</h5>
                                        </div>

                                        <?= $this->form()->openTag($form->setAttributes([
                                            'class' => 'form-horizontal',
                                            'role' => 'form'
                                        ])); ?>

                                        <div class="modal-body">
                                            <div class="form-group">
                                                <label class="control-label col-sm-3">
                                                    <?= $this->translate('Name'); ?>
                                                </label>
                                                <div class="col-sm-9">
                                                    <?= $this->formElement($this->form->get('name')->setAttributes([
                                                        'placeholder' => "Eugene",
                                                        'class' => "form-control"
                                                    ])); ?>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label col-sm-3">
                                                    <?= $this->translate('Description'); ?>
                                                </label>
                                                <div class="col-sm-9">
                                                    <?= $this->formElement($this->form->get('description')->setAttributes([
                                                        'placeholder' => "Eugene",
                                                        'class' => "form-control"
                                                    ])); ?>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label col-sm-3">
                                                    <?= $this->translate('Field name'); ?>
                                                </label>
                                                <div class="col-sm-9">
                                                    <?= $this->formElement($this->form->get('field')->setAttributes([
                                                        'placeholder' => "Eugene",
                                                        'class' => "form-control"
                                                    ])); ?>
                                                </div>
                                            </div>
                                        </div>

                                        <?= $this->partial('partial/form-modal-actions.phtml'); ?>
                                        <?= $this->form()->closeTag(); ?>

                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="panel-body">

                    <table class="table table-striped table-hover mails m-0 table table-actions-bar">
                        <thead>
                        <tr>
                            <th style="width: 50px;">#</th>
                            <th><?= $this->translate('Name'); ?></th>
                            <th><?= $this->translate('Description'); ?></th>
                            <th><?= $this->translate('Created At'); ?></th>
                            <th width="1px" class="text-center">
                                <?= $this->translate('Actions'); ?>
                            </th>
                        </tr>
                        </thead>

                        <tbody>
                        <?php /** @var DataType $item */ ?>
                        <?php foreach ($this->paginator as $item) : ?>
                            <tr>
                                <td><?= $this->escapeHtml($item['id']); ?></td>
                                <td><?= $this->escapeHtml($item['name']); ?></td>
                                <td><?= $this->escapeHtml($item['description']); ?></td>
                                <td><?= $this->escapeHtml($item['createdat']); ?></td>
                                <td class="text-center">

                                    <?= $this->partial('partial/actions.phtml', [
                                        'identifier' => $item['id'],
                                        'matchedRouteName' => $this->matchedRouteName
                                    ]); ?>

                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                    <?= $this->paginationControl($this->paginator, 'sliding', 'partial/pagination.phtml', [
                        'route' => $this->matchedRouteName
                    ]); ?>

                </div>

            </div>
        <?php endif; ?>

    </div> <!-- end col -->
</div>