<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Document\CPanel\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

/**
 * Class IndexController
 * @package MSBios\Document\Backend\Controller
 */
class IndexController extends AbstractActionController
{
    /**
     * @return array
     */
    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    /**
     * @return ViewModel
     */
    public function changelogAction()
    {
        return new ViewModel;
    }

    /**
     * @return ViewModel
     */
    public function loginAction()
    {
        /** @var ViewModel $viewModel */
        $viewModel = new ViewModel;
        $viewModel->setTerminal(true);
        return $viewModel;
    }

    /**
     * @return \Zend\Http\Response
     */
    public function logoutAction()
    {
        return $this->redirect()->toRoute('backend/logout');
    }
}
