<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\CPanel;

use Zend\Form\ElementInterface;

$form = $this->form;
$form->prepare();

$this->headScript()
    ->appendFile($this->basePath('limitless/assets/js/plugins/editors/ace/ace.js'));

?>

    <div class="panel panel-flat">

        <div class="panel-body">

            <?= $this->form()->openTag($form->setAttributes([
                'class' => 'form-horizontal',
                'role' => 'form'
            ])); ?>

            <div class="tabbable">
                <ul class="nav nav-tabs nav-tabs-top">
                    <li class="active">
                        <a href="#tab-information" data-toggle="tab">Information</a>
                    </li>
                    <li><a href="#tab-views" data-toggle="tab">Views</a></li>
                    <li><a href="#tab-properties" data-toggle="tab">Properties</a></li>
                    <li><a href="#tab-tabs" data-toggle="tab">Tabs</a></li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="tab-information">
                        <?= $this->partial('partial/element.phtml', [
                            'element' => $form->get('name')
                                ->setAttributes([
                                    'required' => 'required',
                                    'placeholder' => $this->translate('Enter name')
                                ]),
                            'label' => $this->translate('Name'),
                        ]); ?>
                        <?= $this->partial('partial/element.phtml', [
                            'element' => $form->get('description')
                                ->setAttributes([
                                    'required' => 'required',
                                    'placeholder' => $this->translate('Enter name')
                                ]),
                            'label' => $this->translate('Description'),
                        ]); ?>
                    </div>
                    <div class="tab-pane" id="tab-views">
                        <?= $this->partial('partial/element.phtml', [
                            'element' => $form->get('templateid')
                                ->setAttributes([
                                    'required' => 'required',
                                    'placeholder' => $this->translate('Enter name')
                                ]),
                            'label' => $this->translate('Default View'),
                        ]); ?>

                        <?= $this->partial('partial/element.phtml', [
                            'element' => $form->get('templates')
                                ->setAttributes([
                                    'required' => 'required',
                                    'placeholder' => $this->translate('Enter name')
                                ]),
                            'label' => $this->translate('Views'),
                        ]); ?>
                    </div>
                    <div class="tab-pane" id="tab-properties">

                        <button data-toggle="modal"
                                data-target="#property-modal-form-add"
                                class="btn btn-default btn-xs" href="#">
                            <i class="icon-plus2 position-left"></i> Add property
                        </button>

                        <button data-toggle="modal"
                                data-target="#tab-modal-form-add"
                                class="btn btn-default btn-xs" href="#">
                            <i class="icon-plus2 position-left"></i> Add tab
                        </button>

                        <hr>

                        <?php $hasTabs = $form->get('tabs')->count(); ?>
                        <div class="tabbable <?php if (!$hasTabs): ?>hide<?php endif; ?>">

                            <ul class="nav nav-tabs nav-tabs-highlight">
                                <?php foreach ($form->get('tabs') as $i => $tabElement): ?>
                                    <li class="<?php if ($i): ?>active<?php endif; ?>">
                                        <a href="#tab-properties-<?= $i; ?>" data-toggle="tab">
                                            <?= $tabElement->get('name')->getValue(); ?>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>

                            <div class="tab-content">
                                <?php foreach ($form->get('tabs') as $i => $tabElement): ?>
                                    <div class="tab-pane active" id="tab-properties-<?= $i; ?>">
                                        <div class="panel-group accordion-sortable content-group-lg ui-sortable"
                                             id="accordion-controls-1">
                                            <div class="property-item-1 panel panel-white">
                                                <div class="panel-heading">
                                                    <h6 class="panel-title">
                                                        <a data-toggle="collapse"
                                                           data-parent="#accordion-controls-1"
                                                           href="#property-item-1-1"
                                                           aria-expanded="true" class="">
                                                            Property name
                                                        </a>
                                                        <a class="heading-elements-toggle">
                                                            <i class="icon-more"></i>
                                                        </a>
                                                    </h6>
                                                    <div class="heading-elements">
                                                        <ul class="icons-list">
                                                            <li><a data-action="move" class="ui-sortable-handle"></a>
                                                            </li>
                                                            <li><a data-action="close"></a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                <div id="property-item-1-1"
                                                     class="panel-collapse collapse in"
                                                     aria-expanded="true">
                                                    <div class="panel-body">
                                                        <?= $this->partial('partial/element.phtml', [
                                                            'element' => $form->get('templateid')
                                                                ->setAttributes([
                                                                    'required' => 'required',
                                                                    'placeholder' => $this->translate('Enter name')
                                                                ]),
                                                            'label' => $this->translate('Default View'),
                                                        ]); ?>
                                                        <?= $this->partial('partial/element.phtml', [
                                                            'element' => $form->get('templateid')
                                                                ->setAttributes([
                                                                    'required' => 'required',
                                                                    'placeholder' => $this->translate('Enter name')
                                                                ]),
                                                            'label' => $this->translate('Default View'),
                                                        ]); ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="property-item-2 panel panel-white">
                                                <div class="panel-heading">
                                                    <h6 class="panel-title">
                                                        <a data-toggle="collapse"
                                                           data-parent="#accordion-controls-1"
                                                           href="#property-item-2-1"
                                                           aria-expanded="true" class="">
                                                            Property name
                                                        </a>
                                                        <a class="heading-elements-toggle">
                                                            <i class="icon-more"></i>
                                                        </a>
                                                    </h6>
                                                    <div class="heading-elements">
                                                        <ul class="icons-list">
                                                            <li><a data-action="move" class="ui-sortable-handle"></a>
                                                            </li>
                                                            <li><a data-action="close"></a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                <div id="property-item-2-1"
                                                     class="panel-collapse collapse in"
                                                     aria-expanded="true">
                                                    <div class="panel-body">
                                                        <?= $this->partial('partial/element.phtml', [
                                                            'element' => $form->get('templateid')
                                                                ->setAttributes([
                                                                    'required' => 'required',
                                                                    'placeholder' => $this->translate('Enter name')
                                                                ]),
                                                            'label' => $this->translate('Default View'),
                                                        ]); ?>
                                                        <?= $this->partial('partial/element.phtml', [
                                                            'element' => $form->get('templateid')
                                                                ->setAttributes([
                                                                    'required' => 'required',
                                                                    'placeholder' => $this->translate('Enter name')
                                                                ]),
                                                            'label' => $this->translate('Default View'),
                                                        ]); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>

                        </div>

                        <div class="alert alert-warning no-border <?php if ($hasTabs): ?>hide<?php endif; ?>"
                             role="alert">
                            <h4><?= $this->translate('Information message'); ?></h4>
                            <p><?= $this->translate('To start working with properties, you must create at least one tab.'); ?></p>
                        </div>

                    </div>
                    <div class="tab-pane" id="tab-tabs">

                        <a data-toggle="modal"
                           data-target="#tab-modal-form-add"
                           class="btn btn-default btn-xs" href="#">
                            <i class="icon-plus2 position-left"></i> Add tab
                        </a>

                        <hr>

                        <table class="table table-striped mb-20">
                            <thead>
                            <tr>
                                <th class="text-center" style="width: 10px;">#</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th class="text-center" style="width: 10px;">Action</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php foreach ($form->get('tabs') as $i => $tabElement): ?>

                                <tr id="tabs-item-<?= $i; ?>">
                                    <td class="text-center">
                                        <a href="#" class="btn btn-link btn-xs">
                                            <i class="icon-move"></i>
                                        </a>
                                    </td>

                                    <td>
                                        <?php
                                        /** @var ElementInterface $element */
                                        $element = $tabElement->get('name');
                                        $element->setAttribute('class', 'form-control');
                                        $messages = $element->getMessages();
                                        $hasError = count($messages);
                                        ?>

                                        <div class="<?php if ($hasError): ?>has-warning has-feedback<?php endif; ?>">
                                            <?= $this->formElement($element); ?>
                                            <?php if ($hasError): ?>
                                                <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                                                <span class="help-block">
                                                    <?php foreach ($messages as $message): ?>
                                                        <small><?= $message; ?></small>
                                                    <?php endforeach; ?>
                                                </span>
                                            <?php endif; ?>
                                        </div>
                                    </td>

                                    <td>
                                        <?php
                                        /** @var ElementInterface $element */
                                        $element = $tabElement->get('description');
                                        $element->setAttribute('class', 'form-control');
                                        $messages = $element->getMessages();
                                        $hasError = count($messages);
                                        ?>

                                        <div class="<?php if ($hasError): ?>has-warning has-feedback<?php endif; ?>">
                                            <?= $this->formElement($element); ?>
                                            <?php if ($hasError): ?>
                                                <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                                                <span class="help-block">
                                                    <?php foreach ($messages as $message): ?>
                                                        <small><?= $message; ?></small>
                                                    <?php endforeach; ?>
                                                </span>
                                            <?php endif; ?>
                                        </div>
                                    </td>

                                    <td class="text-center">

                                        <a href="#" class="btn btn-danger btn-xs" data-toggle="modal"
                                           data-target="#tab-modal-remove-<?= $i; ?>">
                                            <i class="icon-trash-alt"></i>
                                        </a>

                                        <div id="tab-modal-remove-<?= $i; ?>"
                                             class="tab-remove modal fade text-left">
                                            <div class="modal-dialog modal-sm">
                                                <div class="modal-content">
                                                    <div class="modal-header bg-warning">
                                                        <button type="button" class="close"
                                                                data-dismiss="modal">&times;
                                                        </button>
                                                        <h6 class="modal-title">Information</h6>
                                                    </div>

                                                    <div class="modal-body">
                                                        <h6 class="text-semibold ">Confirmation to delete</h6>
                                                        <p>You really want to delete the selected entry, return or
                                                            repair is
                                                            impossible</p>
                                                    </div>

                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-link" data-dismiss="modal">
                                                            Cancel
                                                        </button>
                                                        <button type="button"
                                                                class="btn btn-danger"
                                                                data-tab-index="1">
                                                            Remove
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <?= $this->formHidden($tabElement->get('id')); ?>
                                        <?= $this->formHidden($tabElement->get('documenttypeid')); ?>
                                        <?= $this->formHidden($tabElement->get('orderkey')); ?>

                                    </td>
                                </tr>

                            <?php endforeach; ?>

                            </tbody>
                        </table>

                    </div>
                </div>

            </div>

            <?= $this->partial('partial/form-actions', [
                'route' => $this->matchedRouteName,
                'form' => $form
            ]); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>

<?php $this->inlineScript()->captureStart();
echo <<<'JS'
    // PHP editor
    var editor = ace.edit("ace");
        editor.setTheme("ace/theme/monokai");
        editor.getSession().setMode("ace/mode/php");
        editor.setShowPrintMargin(false);
        editor.getSession().on("change", function () {
            $('input[name="code"]').val(editor.getSession().getValue());
        });
JS;
$this->inlineScript()->captureEnd();
?>