<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

$this->headScript()
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switch.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switchery.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/uniform.min.js'));
?>

<div class="row">
    <div class="col-md-12">

        <?php if (!$this->paginator->count()) : ?>

            <div class="alert alert-info no-border" role="alert">
                <h4><?= $this->translate('Information message'); ?></h4>
                <p><?= $this->translate('The database is not created at the moment no layout, click "Create new theme" to start working with the theme.'); ?></p>
                <p>
                    <?php if ($this->isAllowed($this->config->get('resource'), 'add')): ?>
                        <a href="<?= $this->url($this->config->get('route_name'), ['action' => 'add']); ?>"
                           class="btn btn-info"><?= $this->translate('Create new theme'); ?></a>
                    <?php endif; ?>
                </p>
            </div>

        <?php else: ?>
            <div class="panel panel-flat">

                <div class="panel-heading">
                    <h6 class="panel-title">
                        &nbsp<a class="heading-elements-toggle"><i class="icon-more"></i></a>
                    </h6>
                    <div class="heading-elements">
                        <div class="heading-btn">
                            <?= $this->form()->openTag((new \Zend\Form\Form)->prepare()->setAttributes([
                                'class' => 'heading-form',
                                'method' => 'GET'
                            ]));
                            ?>
                            <div class="form-group has-feedback">
                                <?= $this->formSearch(
                                    (new \Zend\Form\Element\Search('q'))->setAttributes([
                                        'class' => 'form-control',
                                        'placeholder' => $this->translate('Search...')
                                    ])
                                ); ?>

                                <div class="form-control-feedback">
                                    <i class="icon-search4 text-size-base text-muted"></i>
                                </div>
                            </div>
                            <?= $this->form()->closeTag(); ?>

                            &nbsp;

                            <a href="#" class="btn btn-success"><?= $this->translate('Create theme'); ?></a>
                        </div>
                    </div>
                </div>

                <div class="panel-body">

                    <table class="table table-striped table-hover mails m-0 table table-actions-bar">
                        <thead>
                        <tr>
                            <th style="width: 50px;">#</th>
                            <th><?= $this->translate('Name'); ?></th>
                            <th><?= $this->translate('Description'); ?></th>

                            <th><?= $this->translate('Created At'); ?></th>

                            <th width="1px" class="text-center">
                                <?= $this->translate('Actions'); ?>
                            </th>

                        </tr>
                        </thead>

                        <tbody>
                        <?php /** @var \MSBios\Resource\Entity\Setting $item */ ?>
                        <?php foreach ($this->paginator as $item): ?>
                            <tr>
                                <td><?= $this->escapeHtml($item['id']); ?></td>
                                <td><?= $this->escapeHtml($item['name']); ?></td>
                                <td><?= $this->escapeHtml($item['description']); ?></td>
                                <td><?= $this->escapeHtml($item['created_at']); ?></td>
                                <td class="text-center">

                                    <?php /** @var string $identifierTrashModal */ ?>
                                    <?php $identifierTrashModal = "modal-confirm-{$item['id']}"; ?>

                                    <ul class="icons-list">

                                        <li>
                                            <a href="<?= $this->url('cpanel/document-type', [
                                                'action' => 'edit',
                                                'id' => $item['id']
                                            ]); ?>">
                                                <i class="icon-pencil"></i>
                                            </a>
                                        </li>

                                        <li class="text-danger-600">
                                            <a href="#"
                                               data-toggle="modal"
                                               data-target="#<?= $identifierTrashModal; ?>">
                                                <i class="icon-trash"></i>
                                            </a>
                                        </li>

                                    </ul>

                                    <!-- Modal -->
                                    <div class="modal fade"
                                         id="<?= $identifierTrashModal; ?>"
                                         tabindex="-1" role="dialog">
                                        <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title">Are you sure?</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Do you want to delete the entry?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button"
                                                            class="btn btn-default"
                                                            data-dismiss="modal">
                                                        Cancel
                                                    </button>
                                                    <a href="#" class="btn btn-primary">
                                                        Yes, delete it!
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>

                    <?= $this->paginationControl($this->paginator, 'sliding', 'partial/pagination.phtml'); ?>

                </div>

            </div>
        <?php endif; ?>

    </div> <!-- end col -->
</div>