<!-- Main content -->
<div class="content-wrapper">

    <!-- Version 1.4 -->
    <div class="panel panel-flat" id="v_1_4">
        <div class="panel-heading">
            <h5 class="panel-title">Version 1.4 (part 1)</h5>
            <div class="heading-elements">
                <span class="text-muted heading-text">September 1, 2016</span>
                <span class="label bg-blue heading-text">v. 1.4</span>
            </div>
        </div>

        <div class="panel-body">
            <p class="content-group">Version 1.4 consists of 2 parts - first part contains updated libraries to the latest stable versions, fixed reported bugs and general template improvements; second part will include new pages and new components only. Custom pages are still in development and will be out within next couple of weeks. In general, this update doesn't include critical changes, but some of the features were completely re-thought: hiding panel heading and page header elements is now optional and file structure in Starter Kit has been slightly changed: now each layout uses common LESS and JS files for both main and starters layouts.</p>

            <pre class="language-javascript"><code>// # List of updated plugins
// ------------------------------

[updated]  Bootstrap library - bootstrap.min.js, bootstrap LESS files - to 3.3.7
[updated]  Font Awesome icon set - bundle - to 4.6.3

[updated]  Hover Dropdown extension - hover_dropdown.min.js - to 2.2.1
[updated]  Typeahead engine - typeahead.bundle.min.js to 0.11.1
[updated]  Dual Listbox - duallistbox.min.js - to 3.0.5
[updated]  Select2 library - select2.min.js - to 4.0.3
[updated]  Bootstrap Select library - bootstrap_select.min.js - to 1.11.1
[updated]  Uniform library - uniform.min.js - to 3.0
[updated]  Summernote editor - summernote.min.js - to 0.8.2

[updated]  Ladda extensions - ladda.min.js - to 1.0.0
[updated]  Bootstrap Progress Bars - progressbar.min.js - to 0.9.0
[updated]  Bootbox dialogs extension - bootbox.min.js to 4.4.0
[updated]  Bootpag pagination - bootpag.min.js - to 1.0.7
[updated]  Bootstrap pagination extension - bs_pagination.min.js - to 1.4

[updated]  Spectrum color picker - spectrum.js - to 1.8.0
[updated]  Pickadate pickers - pickadate.js bundle - to 3.5.6
[updated]  Anytime picker - anytime.min.js - to 5.1.2
[updated]  Bootstrap daterange picker - daterangepicker.js - to 2.1.23
[updated]  Moment.js library - moment.min.js and moment_locales.min.js - to 2.14.1

[updated]  ION Range sliders - ion_rangeslider.min.js - to 2.1.4
[updated]  NoUI sliders - nouislider.min.js - to 8.5.1
[updated]  jQuery UI slider pips - slider_pips.min.js - to 1.11.3 (in LTR only)

[updated]  Datatables library - datatables.min.js - to 1.10.12
[updated]  Autofill DT extention - autofill.min.js - to 2.1.2
[updated]  Buttons DT extention - buttons.min.js - to 1.2.1
[updated]  Column Reorder DT extention - col_reorder.min.js - to 1.3.2
[updated]  Fixed Columns DT extention - fixed_columns.min.js - to 3.2.2
[updated]  Fixed Header DT extention - fixed_header.min.js - to 3.1.2
[updated]  Key Table DT extention - key_table.min.js - to 2.1.2
[updated]  Responsive DT extention - responsive.min.js - to 2.1.0
[updated]  Row Reorder DT extention - row_reorder.min.js - to 1.1.2
[updated]  Scroller DT extention - scroller.min.js - to 1.4.2
[updated]  Select DT extention - select.min.js - to 1.2.0
[updated]  Handsontable library - handsontable.min.js - to 0.26.0

[updated]  Image Cropper - cropper.min.js to 2.3.3
[updated]  Typeahead Addresspicker - typeahead_addresspicker.js to the latest version
[updated]  Fancytree library - fancytree.min.js - to 2.18.0
[updated]  Fullcalendar library - fullcalendar.min.js - to 2.9.1
[updated]  Headroom.js extension - headroom.min.js and headroom_jquery.min.js - to 0.9.3
[updated]  Nicescroll custom scrollbar - nicescroll.min.js - to 3.6.8
[updated]  D3.js charting library - d3.min.js - to 3.5.17

[updated]  Plupload file uploader - plupload bundle - to 2.1.9
[updated]  Bootstrap File Input library - fileinput.min.js to 4.3.5



// # List of fixed
// ------------------------------

[fixed]  Wrong horizontal padding in typeahead suggestions menu items in material layout
[fixed]  WYSIHTML5 text editor color picker doesn’t work and doesn't respect text styles
[fixed]  Fullcalendar table overflow is visible on small screens and some responsive issues
[fixed]  Datatable buttons collection dropdown has wrong horizontal padding
[fixed]  Alpaca horizontal selects extra gap between selects
[fixed]  Fancytree Child Counter extension missing styles
[fixed]  Pager has negative bottom margin
[fixed]  Tabs inside panel don’t have padding on mobile
[fixed]  Nested tabs in vertical tabs layout are also vertical
[fixed]  Styled single file input doesn’t respect width if file name is too long
[fixed]  Mega menu isn’t scrollable on mobile if inside fixed secondary navbar
[fixed]  jQuery UI datepicker is hidden if inside jQuery UI dialog
[fixed]  Dropdown menu in material layout inside breadcrumb elements has wrong placement
[fixed]  Bootstrap file input loading indicator has wrong position when loading begins
[fixed]  jQuery UI Select with icons - icons don’t have horizontal spacing
[fixed]  Steps wizard content overflow is hidden, so components inside wizard are partially hidden
[fixed]  Bootstrap select in panel heading elements triggers native select on click
[fixed]  Dropdown submenus on Android don’t open
[fixed]  Breadcrumb line component inside page header in material layout displayed incorrectly
[fixed]  Single styled file inputs are displayed inline on drag&amp;drop page, in material layout
[fixed]  Search field in search and knowledgebase has background color in material layout
[fixed]  Contextual panels don't have background color on mobile, if heading elements are collapsed
[fixed]  Image cropper in Summernote editor has wrong position and appears behind image

[fixed]  RTL layout - typeahead inputs in material layout have wrong direction
[fixed]  RTL layout - fancy box has incorrect position
[fixed]  RTL layout - handsontable tables have wrong styles
[fixed]  RTL layout - daterangepicker is missing RTL direction in plugin configurations



// # List of improvements
// ------------------------------

[improved]  Improved file structure in Starter Kits
[improved]  Removed paths to extra JS files in Handsontable pages
[improved]  gulpfile.js - minifycss replaced with clean-css due to deprecation
[improved]  Improved Typeahead initializations accross JS files
[improved]  Added missing badges component to panel and page header components list
[improved]  Added 3 new examples of Bootbox dialog extension
[improved]  Added option to disable collapsing of heading elements on mobile (using .not-collapsible class added to .heading-elements container)
[improved]  Now heading elements on mobile push content down instead of covering elements below, so that all responsive containers have consistent appearance
[improved]  Panel heading elements now have background color different from panel background color on mobiles
[improved]  Each layout now uses 1 gulp file for main layout and Starter Kits
</code></pre>
        </div>
    </div>
    <!-- /version 1.4 -->


    <!-- Version 1.3 -->
    <div class="panel panel-flat" id="v_1_3">
        <div class="panel-heading">
            <h5 class="panel-title">Version 1.3</h5>
            <div class="heading-elements">
                <span class="text-muted heading-text">April 1, 2016</span>
                <span class="label bg-blue heading-text">v. 1.3</span>
            </div>
        </div>

        <div class="panel-body">
            <p class="content-group">Version 1.3 is another massive update, which has been in development over the past 3 months. This version includes bug fixing for reported issues, new components, new layout, new theme and updated plugins/libraries to the latest stable versions. Also includes significant improvements of LESS files structure and RTL layout logic - switched to gulp task, which automatically generates CSS files for RTL version, so now both layout directions use same set of LESS files with a few exceptions. The only benefit - very easy to track changes and update files, downside - requires gulp task runner. But documentation and myself help to solve any kind of issues related to upgrade.</p>

            <pre class="language-javascript"><code>// # List of new components
// ------------------------------

[new]  New layout
[new]  Material design theme for all layouts
[new]  Alpaca forms - JSON driven form generator
[new]  Floating Action Menu - material style floating action button with menu, supports 4 positions
[new]  Panel footer components - a great addition to panel component to display panel header components in panel footer
[new]  Floating labels - display hidden labels on input fields
[new]  New heading components - image thumbnails and inline lists
[new]  New page header options - transparent, light, dark, light image and dark image
[new]  New tabs - vertical left/right, with top icons
[new]  Modal with remote source - configuration example
[new]  Navbar navigation - added status mark support
[new]  Forms - added large and extra large input sizes
[new]  Footer - now footer can be either text or navbar component (static and fixed)
[new]  Components animation - added optional transitions to all components, now they are animated by default



// # List of updated plugins
// ------------------------------

[updated]  PNotify notifications - pnotify.min.js - to 3.0.0
[updated]  Noty notifications - noty.min.js - to 2.3.8

[updated]  Datatables library - datatables.min.js - to 1.10.11 and extensions
[updated]  Autofill extension - autofill.min.js - to 2.1.1
[updated]  Buttons extension - buttons.min.js - to 1.1.2
[updated]  Column reorder extension - col_reorder.min.js - to 1.3.1
[updated]  Fixed columns extension - fixed_columns.min.js - to 3.2.1
[updated]  Fixed header extension - fixed_header.min.js - to 3.1.1
[updated]  Key table extension - key_table.min.js - to 2.1.1
[updated]  Responsive extension - responsive.min.js - to 2.0.2
[updated]  Row reorder extension - row_reorder.min.js - to 1.1.1
[updated]  Scroller extension - scroller.min.js - to 1.4.1
[updated]  Select extension - select.min.js - to 1.1.2

[updated]  Select2 library - select2.min.js - to 4.0.2
[updated]  ECharts charting library - echarts.js - to 2.2.7
[updated]  FullCalendar - fullcalendar.min.js - to 2.6.1
[updated]  Dropzone file uploader - dropzone.min.js - to 4.3.0 (done, replace dropzone.less everywhere)
[updated]  Plupload file uploader - plupload.full.min.js - to 2.1.8
[updated]  D3.js visualization library - d3.min.js -  to 3.5.16
[updated]  Noui slider - nouislider.min - to 8.3.0 (done)
[updated]  BlockUI extension - blockui.min.js - to 2.7.0
[updated]  Jasny Bootstrap - jasny_bootstrap.min.js - to 3.1.3
[updated]  Passy - passy.js - to the latest version
[updated]  Auto growing textarea - autosize.js - to 3.0.15 (requires fixes in form_controls_extended.js) (done)
[updated]  Bootstrap selects - bootstrap_select.min.js - to 1.10.0 (requires fixes in bootstrap-select.less) (done)
[updated]  Touchspin spinners - touchspin.min.js - to 3.1.1
[updated]  Bootstrap tags input - bootstrap_tagsinput.min.js - to 0.8.0
[updated]  Form validation - validate.min.js - to 1.15.0 (also needs to be updated form_validation.js - replace card with creditcard)
[updated]  Summernote editor - summernote.min.js - to 0.8.1 (needs new font files to be added)
[updated]  Hideable navbar - headroom.min.js - to 0.8.0
[updated]  Bootstrap file input - file-input.min.js - to 4.3.1
[updated]  Handlebars - handlebars.min.js - to 4.0.5



// # List of fixed
// ------------------------------

[fixed]  Extra horizontal scrollbar in Fullcalendar in Firefox
[fixed]  Multiple Select2 - wrong cross icon placement in FF
[fixed]  Container height hack for FF caused footer issues on mobile
[fixed]  Select2 multiple select with custom bg color - wrong placeholder color
[fixed]  Typo in navbar.less, which caused compilation warnings
[fixed]  When collapsing/expanding sidebar category, class name is added to a wrong item
[fixed]  Panel heading - incorrect vertical alignment in icons and text (wrong calculation)
[fixed]  Descriptions list have incorrect titles on mobiles
[fixed]  If badges have border, border radius is too small to make them rounded
[fixed]  Panel heading - wrong position of tabs and pills
[fixed]  Incorrect height of ION range slider
[fixed]  noUI vertical slider has wrong range width
[fixed]  Color picker overflows fixed navbar
[fixed]  Growl notification generated by BlockUI has double border
[fixed]  jQuery UI selects - long text overlaps arrow icon
[fixed]  Dropzone icon marks appear on the left side overflowing thumb
[fixed]  In 3rd and 4th layout, collapsed sidebar has extra top spacing
[fixed]  Links with default bootstrap contextual background colors have wrong colors on hover/focus
[fixed]  If panel is collapsed by default, arrow icon isn’t rotated
[fixed]  Single daterange picker with time picker - empty calendars container shows up
[fixed]  Floating button inside page header (link buttons) don’t have vertical padding
[fixed]  On mobiles, flat button inside navbar has wrong color text color
[fixed]  Invoice template first row has wrong breakpoint
[fixed]  Datatables doesn’t have horizontal spacing in header/footer if table is inside form
[fixed]  Hideable navbar doesn’t support optional navbar sizes
[fixed]  Border radius inconsistency in input elements
[fixed]  In RTL version page title subtitle has wrong position
[fixed]  Icon inside input group disappears when input is focused
[fixed]  Default and flat labels/badges heights are inconsistent
[fixed]  Pagination and pager have extra bottom spacing
[fixed]  Datatables fixed columns extension - complex header example not resizable
[fixed]  Dual list boxes inconsistent border radiuses



// # List of improvements
// ------------------------------

[improved]  Improved *-sm and *-xs styles in inputs, buttons, selects and input groups
[improved]  Additional placements of labels/badges in dropdown (badges/labels are always on the far right)
[improved]  Fancy box close button position
[improved]  Added horizontal spacing to images inside user dropdown menu
[improved]  Single styled file input (supports text and icons with all available button styles)
[improved]  Use buttons instead of inputs in steps actions
[improved]  Label/badge and flat label/badge size inconsistency
[improved]  Increased caret width
[improved]  Added .no-shadow helper class - removes shadow from element
[improved]  Tabs inside panel header
[improved]  Add direction: ltr; to all tags to avoid issues in RTL version
[improved]  Removed input highlights in contextual feedback states
[improved]  Look and feel of CKEditor toolbar
[improved]  Added multiselect dropdown support to navbar
[improved]  Sidebar navigation appearance
[improved]  RTL version - switched to gulp task, that automatically generates RTL version from LTR, to avoid problems with updates
[improved]  Significantly improved LESS file structure
</code></pre>
        </div>
    </div>
    <!-- /version 1.3 -->


    <!-- Version 1.2.1 -->
    <div class="panel panel-flat" id="v_1_2_1">
        <div class="panel-heading">
            <h5 class="panel-title">Version 1.2.1</h5>
            <div class="heading-elements">
                <span class="text-muted heading-text">December 15, 2015</span>
                <span class="label bg-blue heading-text">v. 1.2.1</span>
            </div>
        </div>

        <div class="panel-body">
            <p class="content-group">Version 1.2.1 is a quick update that contains some reported bugs fixes and plugins update. Nothing new is added since this is an addition to global 1.2 version. Important milestone for 1.3 version is footer and container height enhancements - jquery solution for calculating minimum container height will be replaced with pure CSS.</p>

            <pre class="language-javascript"><code>// # List of updated plugins
// ------------------------------

[updated]  Bootstrap file input - to the latest version
[updated]  Select2 - from RC1 to stable 4.0.1 version


// # List of fixed bugs
// ------------------------------

// Core fixes
[fixed]  Documentation - correct release date on main page, fixed path to globalize/ library, gulp plugins to install
[fixed]  Navbar - added sticky sidebar top spacing if used with fixed top single navbar. To be enhanced in 1.3
[fixed]  Fixed sidebar and navbar - removed unnecessary affix code from the page

// Components fixes
[fixed]  Centered timeline - extra dots on desktop
[fixed]  Datatables Select extension - checkboxes are not selectable
[fixed]  Datatables Autofill and Select - wrong columns sorting in examples with checkboxes
[fixed]  Select2 selects - selected text overlaps arrow in single select
[fixed]  Select2 selects validation - wrong error/success label placement
</code></pre>

        </div>
    </div>
    <!-- /version 1.2.1 -->


    <!-- Version 1.2 -->
    <div class="panel panel-flat" id="v_1_2">
        <div class="panel-heading">
            <h5 class="panel-title">Version 1.2</h5>
            <div class="heading-elements">
                <span class="text-muted heading-text">December 2, 2015</span>
                <span class="label bg-blue heading-text">v. 1.2</span>
            </div>
        </div>

        <div class="panel-body">
            <p class="content-group">Version 1.2 includes bug fixing for reported issues, new components and updated plugins/libraries to the latest stable versions. Also i've included <code>gulp</code> file to simplify development process, including <code>package.json</code> file. New components added: <strong>Handsontable</strong> library, <strong>Dragula</strong> drag and drop library, full set of jQuery UI components, new <strong>Select2</strong> version and updated examples, full set of <strong>Datatables</strong> extensions and new <strong>login</strong> pages. Changes in this update affect all layouts, both LTR and RTL directions.</p>

            <pre class="language-javascript"><code>// # List of new components
// ------------------------------

[new]  Handsontable - excel-like spreadsheet for apps
[new]  Dragula - drag and drop library
[new]  jQuery UI - full set of components
[new]  Row Reorder - Datatables extension
[new]  Fixed Header - Datatables extension
[new]  Auto Fill - Datatables extension
[new]  Key Table - Datatables extension
[new]  Select - Datatables extension
[new]  Buttons - Datatables extension
[new]  Login/registration form with validation
[new]  Login/registration forms inside modals
[new]  Login/registration form inside tabs
[new]  Vertical navigation with labels and badges
[new]  Ion Range Sliders - responsive range slider library
[new]  gulpfile.js and package.json for Gulp task runner


// # List of updated plugins
// ------------------------------

[updated]  Bootstrap library - to version 3.3.6
[updated]  jQuery UI library - to the latest version (1.11.4)
[updated]  Select2 - to version 4.0.1, including examples
[updated]  Sweet Alerts - to the latest version, including examples
[updated]  Datatables - to the latest version (1.10.10)
[updated]  Daterangepicker - to the latest version (2.1.13)
[updated]  NoUI sliders library - to the latest version (8.1.0)
[updated]  Velocity animations library - to the latest version (1.2.3 and 5.0.4)
[updated]  i18next internationalization library - to the latest version (1.11.1)


// # List of fixed bugs
// ------------------------------

// Core fixes
[fixed]  Filled page header - extra scroll when content height is smaller than page height (2nd, 3rd and 4th layouts)
[fixed]  Vertical navigation sizing in Mini sidebar mode (wrong top spacing in sub menu)
[fixed]  Added missing margin and padding helper classes to the helpers table

// Components fixes
[fixed]  Login/registration and error pages - jump on page load
[fixed]  Removed modals with remote source as deprecated in 3.3.0 version (to be replaced with AJAX modals)
[fixed]  Badges now have transparent background color by default - no dependency on parent container bg color
[fixed]  Form wizard with validation - doesn’t go to the second step when all inputs filled
[fixed]  Daterangepicker picker - invisible text in selects
[fixed]  Incorrect date format in daterangepicker in RTL version
[fixed]  Daterange single date picker extra horizontal spacing
[fixed]  Fancybox lightbox jumps to the top of the page on button click
[fixed]  Fancybox loading icon doesn't show up
[fixed]  Blockquote footer overlapping
[fixed]  NoUI slider RTL direction support
[fixed]  Bootstrap tags input RTL Typeahead input direction (appears in LTR direction)
[fixed]  jQuery UI datepicker selects wrong margin that causes stacking
[fixed]  Form control feedback icon inside input group is hidden on focus
[fixed]  Horizontal multi level menu with nice scroll causes js error, because initialized twice


// # List of enhancements
// ------------------------------

[enhanced]  Added extra styles for syntax highlighter, doesn't look so boring with stripes
[enhanced]  Re-structured less files for tables, now they more organized
[enhanced]  Changed structure of jQuery UI components and less files - grouped by widgets, effects, core and interactions
[enhanced]  jQueryUI and NoUI sliders default color changed from grey to dark blue


// # List of new pages
// ------------------------------

[new page] navigation_vertical_labels_badges.html
[new page] jqueryui_interactions.html
[new page] jqueryui_forms.html
[new page] jqueryui_components.html
[new page] jqueryui_navigation.html
[new page] extension_dnd.html
[new page] datatable_extension_row_reorder.html
[new page] datatable_extension_fixed_header.html
[new page] datatable_extension_autofill.html
[new page] datatable_extension_key_table.html
[new page] datatable_extension_select.html
[new page] datatable_extension_buttons_init.html
[new page] datatable_extension_buttons_flash.html
[new page] datatable_extension_buttons_print.html
[new page] datatable_extension_buttons_html5.html
[new page] handsontable_basic.html
[new page] handsontable_advanced.html
[new page] handsontable_cols.html
[new page] handsontable_cells.html
[new page] handsontable_types.html
[new page] handsontable_custom_checks.html
[new page] handsontable_ac_password.html
[new page] handsontable_search.html
[new page] handsontable_context.html
[new page] login_validation.html
[new page] login_tabbed.html
[new page] login_modals.html


// # List of removed components
// ------------------------------

[removed] TableTools - Datatables extension
[removed] ColVis - Datatables extension
</code></pre>
        </div>
    </div>
    <!-- /version 1.2 -->


    <!-- Version 1.1 -->
    <div class="panel panel-flat" id="v_1_1">
        <div class="panel-heading">
            <h5 class="panel-title">Version 1.1</h5>
            <div class="heading-elements">
                <span class="text-muted heading-text">October 21, 2015</span>
                <span class="label bg-blue heading-text">v. 1.1</span>
            </div>
        </div>

        <div class="panel-body">
            <p class="content-group">First update is the most simplified and includes urgent bug fixes of core components, plugins and libraries. Also version 1.1 includes updates of some components to the latest stable versions. The only new thing here is RTL version of all 4 layouts, that support almost all available components and layout features. Below you can find general list of all changes and details about upgrading.</p>

            <pre class="language-javascript"><code>// # List of new components
// ------------------------------

[new]  RTL layout for all 4 main layout variations
[new]  bootbox.less - new LESS file for extended Bootstrap modal dialogs


// # List of updated plugins
// ------------------------------

[updated]  CKEditor - latest version
[updated]  Select2 - latest 3.5.x version, 4.0 is coming
[updated]  Bootstrap Multiselect - latest version
[updated]  Datatables - latest version


// # List of fixed bugs
// ------------------------------

// Core fixes
[fixed]  Sidebar - side border overlaped content in light sidebar (layout 1 and 2)
[fixed]  Breadcrumbs - in colored version links had wrong background color on hover/active
[fixed]  Breadcrumbs - dropdown menu didn't have borders in breadcrumb line component
[fixed]  Labels - striped labels didn't have right border variation as supposed to
[fixed]  Navbars - unnecessary dropdown menu re-position in navbar component
[fixed]  Button groups - extra space between buttons in toolbar
[fixed]  Tables - extra border in framed table in responsive table container

// Components fixes
[fixed]  Bootstrap Select - wrong rounded corners inside input group
[fixed]  Bootstrap Select - no styling of dropdown menu
[fixed]  SelectBox - wrong rounded corners inside input group
[fixed]  Tags Input - input field didn't have bottom spacing
[fixed]  Typeahead - small menu width if text options are too short
[fixed]  Sweet alerts - title was too big for motification size
[fixed]  Anytime picker - wrong title margin and unnecessary close button
[fixed]  jQuery UI Datepicker - extra RTL-related code in less file
[fixed]  Fullcalendar - extra RTL-related code in less file
[fixed]  Chats - wrong variables in LESS file
[fixed]  Dropzone Uploader - success/error markers moved down in thumbnails is name is visible
[fixed]  Colors - default BS styles overrided text hover state
[fixed]  SelectBox page - extra panel control buttons
</code></pre>
        </div>
    </div>
    <!-- /version 1.1 -->


    <!-- Initial release -->
    <div class="panel panel-flat" id="release">
        <div class="panel-heading">
            <h5 class="panel-title">Initial release</h5>
            <div class="heading-elements">
                <span class="text-muted heading-text">October 1, 2015</span>
                <span class="label bg-blue heading-text">v. 1.0</span>
            </div>
        </div>

        <div class="panel-body">
            Limitless is in active development. All updates will be properly documented and explained, to make your upgrade process as easy as possible. In all new updates will be included: bug fixing, new functionality, plugins version control and code improvement. Feel free to contact me if you have any suggestions or requests!
        </div>

        <div class="table-responsive">
            <table class="table table-bordered table-striped table-xs">
                <thead>
                <tr>
                    <th class="col-xs-3">What</th>
                    <th>Quantity</th>
                    <th>Description</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th colspan="3" class="active">Core files</th>
                </tr>
                <tr>
                    <td>Folders</td>
                    <td>268</td>
                    <td>Folders with files, excluding CKEditor and Starter kit folders</td>
                </tr>
                <tr>
                    <td>HTML files</td>
                    <td>249</td>
                    <td>Depending on layout, around 249 main HTML files in each layout</td>
                </tr>
                <tr>
                    <td>CSS files</td>
                    <td>7</td>
                    <td>4 main CSS files, 2 CSS for icon fonts and 1 <code>animate.min.css</code> animation library</td>
                </tr>
                <tr>
                    <td>LESS files</td>
                    <td>203</td>
                    <td>All LESS files, including Bootstrap core</td>
                </tr>
                <tr>
                    <td>JS files</td>
                    <td>896</td>
                    <td>All JS files, excluding starter kit and CKEditor folders</td>
                </tr>
                <tr>
                    <td>Image files</td>
                    <td>256</td>
                    <td>Logos, flag icons and notification icons</td>
                </tr>
                <tr>
                    <th colspan="3" class="active">Other files</th>
                </tr>
                <tr>
                    <td>JSON files</td>
                    <td>23</td>
                    <td>Different demo data sources. For demo purposes</td>
                </tr>
                <tr>
                    <td>CSV files</td>
                    <td>11</td>
                    <td>Mainly for charts based on <code>D3.js</code> library. For demo purposes</td>
                </tr>
                <tr>
                    <td>TSV files</td>
                    <td>13</td>
                    <td>Mainly for charts based on <code>D3.js</code> library. For demo purposes</td>
                </tr>
                <tr>
                    <td>SWF files</td>
                    <td>3</td>
                    <td>Additional files for datatables TableTools extension and Plupload file uploader</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!-- /initial release -->

</div>
<!-- /main content -->